dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install parso codecov coverage
script:
  - coverage run test_bpc_utils.py
after_success:
  - codecov
