name: Python Lint and Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install flake8 pylint mypy bandit vermin>=0.10.3 colorlabels
    - name: Run linters
      run: python ci/run_linters.py
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
        python-version: [3.4, 3.5, 3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install . pytest>=4.5.0 coverage codecov
    - name: First round test (local code, with coverage)
      run: |
        python ci/path_checker.py
        coverage run -m pytest
    - name: Second round test (installed package, without coverage)
      run: |
        mv bpc_utils bpc_utils~
        python ci/path_checker.py strict
        pytest
        mv bpc_utils~ bpc_utils
    - name: Upload coverage report
      run: codecov
